### PR TITLE
Added support for ability_upgrades, tests, comments and documentation updates

### PR DESCRIPTION
**Pull request by bodrovis**
Added new `Ability` class to list all abilities picked by player.

### CODE REVIEW

**Comment by bodrovis** [comment]
https://github.com/vinnicc/dota/commit/83bc873537f3eee10c24d9ef8ce2c68deb00ac33#diff-be6894217cc3da9f9d80f4bca6332609R40

API also provides two more fields: `time` (second since the start of the game when the abilitiy was learned) and `level` (integer, at which level the ability was learned), however this probably should not be included as a class attributes. Maybe we could generate an array of hashes there, like:

```
[
  {ability: Ability.new(raw_ability_upg["ability"]),
  time: raw_ability_upg["time"],
  level: raw_ability_upg["level"]
  }
]
```

**Comment by vinnicc** [comment]
Thanks, this is something I've been meaning to add. I'll test it later today.

On another note, any idea on how to work around the failing builds? :)

**Comment by bodrovis** [comment]
@vinnicc Ok cool. I did some researching on this and seems like this might be the solution https://stackoverflow.com/questions/9338428/using-secret-api-keys-on-travis-ci#12778315 Could you try that?

**Comment by vinnicc** [comment]
Just needs a rebase after https://github.com/vinnicc/dota/pull/13.

**Comment by vinnicc** [comment]
With regard to the keys, I remember trying it and finding out that it's only good for one repo. The PRs were still failing. Maybe contributors should put their own `STEAM_API_KEY` on Travis? Because you can, under the repo's Settings > Environment Variables.

**Comment by bodrovis** [comment]
There are merge conflicts that I can't fix :( Closing this in favor of https://github.com/vinnicc/dota/pull/15

**Pull request closed without merging**
