### PR TITLE
Update abilities and items

### PR DESCRIPTION
**Pull request by bodrovis**
https://github.com/bodrovis/Sitepoint-source/issues/2#issuecomment-102775941 that's why I love feedback :) It appears that whole bunch of new items were added (http://www.dota2.com/items/), so I updated the corresponding yaml file. Unfortunately, some of those items also have recepies but I wasn't able to find their ids anywhere.

### CODE REVIEW

**Comment by bodrovis** [comment]
Ah, found it.

**Comment by vinnicc** [comment]
Thanks for this!

**Comment by bodrovis** [comment]
Dont merge!

**Comment by bodrovis** [comment]
:)
a second

**Comment by bodrovis** [comment]
I've found some other fancy stuff http://dota2.e-sportsbulletin.com/dota-2-6-84-changelog/

**Comment by bodrovis** [comment]
@vinnicc Ok, now it is ready to be merged :)

**Comment by vinnicc** [comment]
@bodrovis Okay, awesome work!

**Comment by bodrovis** [comment]
@vinnicc Could you publish a new version of the gem? :) I'd update my demo app then.

**Comment by vinnicc** [comment]
@bodrovis Done!

**Comment by bodrovis** [comment]
Cool!

**Pull request merged**
