### PR TITLE
Update faraday to 0.9.1

### PR DESCRIPTION
**Pull request by bodrovis**

### CODE REVIEW

**Comment by bodrovis** [comment]
I am not quite sure where to provide API key for build to pass, but on my local machine everything was fine.

**Comment by vinnicc** [comment]
Yeah, let me know if you figure out a way to work around it. Thanks!

**Comment by bodrovis** [comment]
@vinnicc Could you please run the tests on your PC? Do you get any errors related to `SecureRandom`?

**Comment by vinnicc** [comment]
@bodrovis I did before merging, no errors!

**Pull request merged**
