### PR TITLE
Format tower and barracks status, add new fixtures, tweak tests

### PR DESCRIPTION
**Pull request by bodrovis**
Barracks and tower status does not return binary anymore - it returns decimal numbers. So I thought it would be nice to return hash instead to mark which towers and barracks were standing.

I've also added a new cassette instead of an old one - this one seems to be more representative (various states of towers/barracks, summoned units are present). On DotaBuff: http://www.dotabuff.com/matches/1430857330 (I've compared results, everything seems to be okay).

If you think this looks good, I'll add another commit here to reflect changes in the docs.

### CODE REVIEW

**Comment by vinnicc** [comment]
Looks good, will merge after documentation updates. Thanks!

**Comment by bodrovis** [comment]
Fixed the issues.

By the way, LiveMatch also has these methods: https://github.com/vinnicc/dota/blob/master/lib/dota/api/live_match/side.rb#L21 but they are not mentioned in the docs. I'll check if this is working correctly. If yes, we can add `BasicSide` class and extract some methods there.

**Comment by vinnicc** [comment]
That would be great. If it doesn't make much sense to inherit from another class, I'm open to adding a `BarracksStatus` class and just passing the hash upon initialization.

**Comment by bodrovis** [comment]
Okay, I've added `BasicSide` to extract some common stuff as tower and barracks status are still working for live matches as well. Seems like work on this branch is complete :)

**Pull request merged**
