### PR TITLE
Two small issues

### PR DESCRIPTION
**Pull request by yielder**
- The first item in the data list called empty, which is invalid.
- Image url for recipe_eg.png doesn't exist.

### CODE REVIEW

**Comment by bodrovis** [comment]
Yeah, judging by this http://www.dota2.com/jsfeed/itemdata?l=english Empty does not exist anymore, however it used to be there.

Same thing regarding `eg` - seems like it was removed.

**Comment by yielder** [comment]
When I tried to pull down all the item images, I found that not just the "recipe_eg.png" was missing. Ten other items starts with recipe also were missing from the server no matter the type is eg or lg.

Eg:
http://cdn.dota2.com/apps/dota2/images/items/recipe_glimmer_cape_eg.png
http://cdn.dota2.com/apps/dota2/images/items/recipe_silver_edge_eg.png
etc...

All these items seem to be the new items in 6.84.

So, I suggest that when encounter the recipe item, it's probably best to just remove "recipre_" prefix and return the origin item image instead.  :)

**Comment by vinnicc** [comment]
We'd still need a way to distinguish between the recipe and original item right, perhaps a `recipe?` method?

Or we could use another item that returns a recipe image and use that for `:eg`. Something like, but not necessarily [`mystery_vacuum_eg.png`](http://cdn.dota2.com/apps/dota2/images/items/mystery_vacuum_eg.png) :smile:.

**Comment by yielder** [comment]
I added a recipe? method for the item class.

Also, I found that recipe item's name return is hash object instead of string
For example: 
@name={"Recipe"=>"Magic Wand"} should be  @name="Recipe Magic Wand"
So I added quotes around those items to escape the colon in the item.yml file.
:smile:

**Comment by vinnicc** [comment]
Good catch on the unquoted strings! Just let me know when you're ready to merge this.

**Comment by yielder** [comment]
Ok, please merge this if you're ok with it. My first request to be merged. :smile:

**Comment by bodrovis** [comment]
Everyting seems to be fine!

**Comment by vinnicc** [comment]
I just had to put back `empty` because the blank inventory slots were failing some tests. https://github.com/vinnicc/dota/commit/8f9848f869b6bd0e47acd1a987f68967255753fd

**Pull request merged**
